"""Run selected Path-ND QC components on a single slide.

    pathnd-qc --slide slide.svs --run_tissue_segmentation
    pathnd-qc --slide slide.svs --tissue_mask mask.png --run_fold_detection
    pathnd-qc --list_components

Components consume artifacts declared in ``pipeline_spec.py``. The thumbnail, three masks and
selected tile list can be supplied from files; other outputs are generated by their producers.
Known argument and supplied-file errors are checked before slide reads. Geometry, remote access
and model failures can still occur during processing. Reports and partial outputs are saved on a
best-effort basis, including on failure when the destination remains writable.

Local, GCS, S3 and Azure slides share the reader. Tile reads use a localized copy; M2/M4 normally
stream an analysis plane, with localization for remote inputs that require banded reading.
Default target scales are 8.0 microns/pixel for M2/M4 and 0.5 for M3. Integer dimensions introduce
rounding, and common scale alone does not establish scientific comparability.

Metadata lookup uses only user-supplied CSV paths. No paths means no lookup. M4's shipped reference
targets are placeholders, not calibrated neuropathology references. See USAGE_CLI.md for contracts.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import json
import math
import os
import signal
import threading
from contextlib import ExitStack
from functools import wraps
import sys
import time
import traceback
from pathlib import Path

import numpy as np

from pathnd_qc import artifact_store as store
from pathnd_qc._fs import slide_id
from pathnd_qc import pipeline_spec as spec
from pathnd_qc._logging import get_logger
from pathnd_qc.config.config import cfg, config_error, error_kind, now_stamps, provenance, resolve_out_dir
from pathnd_qc._logging import RUN_ID as _RUN_ID, configure_logging
from pathnd_qc.ingestion.wsi_reader import wsi_reader as m1_wsi
from pathnd_qc.ingestion.wsi_reader.wsi_reader import GCSWSIReader, resolve_mpp_level, slide_mpp
from pathnd_qc.ingestion.ingestion_checks.ingestion_checks import (apply_scale, build_ingestion_record,
                                                             check_integrity, check_magnification,
                                                             check_mpp, decide)
from pathnd_qc.ingestion.ingestion_checks import ingestion_checks as m1_checks
from pathnd_qc.ingestion.metadata import metadata as m1_meta
from pathnd_qc.qc_slide.pen import pen as m2_pen
from pathnd_qc.qc_slide.tissue import tissue as m2_tissue
from pathnd_qc.qc_slide.folds import folds as m2_folds
from pathnd_qc.qc_slide.staining import staining as m2_staining
from pathnd_qc.qc_slide.focus import focus as m2_focus
from pathnd_qc.qc_tile.tiles.tiles import select_tissue_tiles
from pathnd_qc.qc_tile.tile_metrics import tile_metrics as m3_tiles
from pathnd_qc.qc_tile.artifacts import artifacts as m3_artifacts
from pathnd_qc.normalization.stain_norm import stain_norm as m4_norm
from pathnd_qc.reporting.reporting import build_report, write_report
from pathnd_qc import output_layout, result_browser

M2_TARGET_MPP = cfg("m2.read.target_mpp", 8.0)
M4_METHOD = cfg("m4.method", "macenko")

class _Skipped(dict):
    """A component that did not run. Present in the report with a reason, never absent, never zero."""

    def __init__(self, why: str):
        super().__init__(runtime_s=0.0, error=f"skipped: {why}")


def _skip(why: str) -> dict:
    return dict(_Skipped(why))


def _not_selected(component: str) -> str:
    if not cfg(f"components.{component}", True):
        return f"disabled by components.{component}=false"
    return f"{spec.COMPONENTS[component]['flag']} not given"


def _supplied_reason(artifact: str) -> str:
    reason = f"supplied via {spec.ARTIFACTS[artifact]['flag']}"
    producer = spec.ARTIFACTS[artifact]["produced_by"]
    if producer and not cfg(f"components.{producer}", True):
        reason += f"; {_not_selected(producer)}"
    return reason


class RunFailed(RuntimeError):
    """A processing failure carrying its in-memory report and attempted report destination.

    ``failure`` contains stage, type, message and traceback. Persistence is best effort: a
    filesystem failure can prevent a report from reaching ``report_path``.
    """

    def __init__(self, failure: dict, report: dict, report_path):
        super().__init__(f"run failed during {failure['stage']}: "
                         f"{failure['type']}: {failure['message']}")
        self.failure, self.report, self.report_path = failure, report, report_path


# results key -> component key, for marking what a failed run never reached; and results key ->
# the supplied artifact that stands in for that component, so a mask that failed to load is
# reported as exactly that rather than as "flag not given".
_RESULT_KEYS = {s["report_key"]: name for name, s in spec.COMPONENTS.items()
                if name != "tile_selection"}  # geometry is reported separately from measurements
_SUPPLIED_FOR = {s["report_key"]: artifact for s in spec.COMPONENTS.values()
                 for artifact in s["produces"] if spec.ARTIFACTS[artifact]["kind"] == "mask"}


def _supplied_mask(name: str, supplied: dict, hw, inputs: dict):
    """Load a supplied mask or raise an error naming its flag. A failed load cannot become a missing mask."""
    got = store.load_mask(supplied[name], hw, allow_empty=name in {"pen_mask", "fold_mask"})
    if got["error"]:
        raise ValueError(f"{spec.ARTIFACTS[name]['flag']}: {got['error']}")
    inputs[name] = got["provenance"]
    return got["mask"]


def _with_run_id(fn):
    """Scope correlation to one call while preserving its public signature and documentation."""
    @wraps(fn)
    def wrapped(slide_path: str, **kwargs):
        token = _RUN_ID.set(_slide_id(str(slide_path)))
        try:
            return fn(str(slide_path), **kwargs)
        finally:
            _RUN_ID.reset(token)
    return wrapped


def _preflight_files(slide_path, *, norm_method, pen_weights, grandqc_repo, run_set,
                     metadata_paths, metadata_key, metadata_enabled, out_dir, prepare_output=True):
    """Validate known inputs and the output directory before any slide I/O."""
    # Validate required paths and options before downloading or reading the slide.
    if norm_method is not None and norm_method not in m4_norm.METHODS:
        raise ValueError(f"--norm_method: {norm_method!r} is not one of {sorted(m4_norm.METHODS)}")
    if "pen_detection" in run_set:
        if pen_weights and not os.path.isfile(pen_weights):
            raise ValueError(f"pen_detection --pen_weights: expected a readable file: {pen_weights}")
        weights = pen_weights or m2_pen.DEFAULT_WEIGHTS
        if not weights or not os.path.isfile(weights) or not os.access(weights, os.R_OK):
            raise ValueError("pen_detection requires readable model weights: "
                             f"{weights or '(not configured)'}. Run 'pathnd-qc setup pen' "
                             "or supply --pen_weights /path/to/pen.pt.")
    if "tile_artifacts" in run_set:
        problem = m3_artifacts.check_grandqc_repo(grandqc_repo)
        if problem:
            raise ValueError(f"tile_artifacts requires GrandQC: {problem}. "
                             "Run 'pathnd-qc setup grandqc' or supply --grandqc_repo.")
    if "://" not in str(slide_path) and not os.path.isfile(slide_path):
        raise ValueError(f"--slide: file not found: {slide_path}\n"
                         f"  --slide expects a readable WSI path: a local file or GCS, S3 or Azure object URI.")
    for p in (metadata_paths or []):
        if "://" not in str(p) and not os.path.isfile(p):
            raise ValueError(f"--metadata: expected a readable file: {p}")
    if out_dir is not None and not str(out_dir).strip():
        raise ValueError("--out: expected a nonempty directory path")
    if metadata_enabled is False and (metadata_paths or metadata_key):
        raise ValueError("--no_metadata cannot be combined with --metadata/--metadata_key")
    if metadata_key and not metadata_paths:
        raise ValueError("--metadata_key requires --metadata")

    base_out = resolve_out_dir(out_dir)     # absolute, resolved against the caller's cwd
    if base_out.exists() and not base_out.is_dir():
        raise ValueError(f"--out: {base_out} exists and is not a directory")
    if not prepare_output:
        return base_out
    try:
        base_out.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise ValueError(f"--out: cannot create {base_out}: {exc}") from exc
    if not os.access(base_out, os.W_OK):
        raise ValueError(f"--out: {base_out} is not writable")
    return base_out


@dataclass
class _RunContext:
    """Shared state for one run, its stage helpers, and report assembly.

    Stage helpers mutate result dictionaries and assign acquisition, stain, and read
    metadata as they produce them. Fields stay None or empty when their stage does not run.
    """
    slide_path: str
    slide_id: str
    plan: dict
    ran: set
    supplied: dict
    out_dir: Path | None = None
    output_root: Path | None = None
    stain_type: str | None = None
    save_artifacts: bool = True
    grandqc_repo: str | None = None
    grandqc_python: str | None = None
    grandqc_source: str | None = None
    run_set: set = field(default_factory=set)       # the requested components (`ran` is the planned order)
    bank: str | None = None
    norm_method: str | None = None
    pen_weights: str | None = None
    write: bool = True
    meta_sources: list | None = None
    metadata_enabled: bool | None = None
    inputs: dict = field(default_factory=dict)      # provenance.inputs — where every artifact came from
    outputs: dict = field(default_factory=dict)     # provenance.outputs records saved artifacts by path
    stage_t: dict = field(default_factory=dict)
    warnings: list = field(default_factory=list)
    results: dict = field(default_factory=dict)
    info: dict | None = None
    checks: dict | None = None
    record: dict | None = None
    localize_info: dict = field(default_factory=dict)
    m2_read: dict | None = None
    run_provenance: dict = field(default_factory=provenance)  # snapshot before slide work begins


@_with_run_id
def run(slide_path: str, *, out_dir: str | None = None, stain_type: str | None = None,
        bank: str | None = None, norm_method: str | None = None,
        components: set | None = None, supplied: dict | None = None,
        grandqc_repo: str | None = None, grandqc_python: str | None = None,
        pen_weights: str | None = None, write: bool = True,
        save_artifacts: bool = True, metadata_paths: list | None = None,
        metadata_key: str | None = None, metadata_enabled: bool | None = None,
        warn=None, download_models: bool = True) -> dict:
    """Run the selected components on one slide.

    `components` names keys from `pipeline_spec.COMPONENTS`; None selects all enabled
    components. Configuration can disable individual components. Missing default models are
    installed automatically unless download_models is False or PATHND_NO_MODEL_DOWNLOAD=1.
    Selected components must complete: setup failures raise ValueError, and incomplete
    runs preserve their report and raise RunFailed.

    `supplied` maps artifact names to paths. Warnings reach `warn(message)` as they
    arise and are included in `provenance.warnings`. Planning warnings precede slide I/O.
    The return value contains per-stage results and the report.

    The run performs preflight, acquisition and M1 checks, analysis, then publication.
    Keywords expose analysis options and Python controls such as write and warn.
    Metadata lookup uses only `metadata_paths`; omission skips lookup.
    """
    t0 = time.monotonic()
    supplied = dict(supplied or {})
    stain_type = (stain_type or "").strip() or None   # Treat empty or whitespace-only strings as an unspecified stain.
    run_set = spec.select_run_set(components)
    # Preserve invalid configured paths so preflight can name the missing setup before slide I/O.
    explicit_repo = grandqc_repo
    grandqc_repo, grandqc_source = m3_artifacts.resolve_repo(grandqc_repo)
    grandqc_python = grandqc_python or cfg("m3.artifacts.python", None)
    plan = spec.plan_run(run_set, supplied, artifact_backend=True)
    if plan["errors"]:
        raise ValueError("\n\n".join(e["message"] for e in plan["errors"]))
    bad = spec.validate_supplied(supplied)   # Plan once with the resolved component selection and backend.
    if bad:
        raise ValueError("\n".join(bad))
    _preflight_files(slide_path, norm_method=norm_method, pen_weights=None,
                     grandqc_repo=None, run_set=set(), metadata_paths=metadata_paths,
                     metadata_key=metadata_key, metadata_enabled=metadata_enabled, out_dir=out_dir,
                     prepare_output=False)
    resolved_repo = grandqc_repo
    from pathnd_qc.external.manager import ensure_models
    automatic = set(run_set)
    if pen_weights:
        automatic.discard("pen_detection")
    if explicit_repo:
        automatic.discard("tile_artifacts")
    pen_weights, grandqc_repo, grandqc_python = ensure_models(
        automatic, pen_weights=pen_weights or m2_pen.DEFAULT_WEIGHTS, grandqc_repo=grandqc_repo,
        grandqc_python=grandqc_python, download_models=download_models)
    if grandqc_repo != resolved_repo:
        grandqc_source = "managed"
    warnings: list = []

    def _warn(message: str):
        warnings.append(message)
        if warn is not None:
            warn(message)
    for w in plan["warnings"]:
        _warn(w)
    if config_error():
        _warn(config_error())

    base_out = _preflight_files(slide_path, norm_method=norm_method, pen_weights=pen_weights,
                                grandqc_repo=grandqc_repo, run_set=run_set,
                                metadata_paths=metadata_paths, metadata_key=metadata_key,
                                metadata_enabled=metadata_enabled, out_dir=out_dir)
    ctx = _RunContext(slide_path=slide_path, slide_id=_slide_id(slide_path), plan=plan,
                      output_root=base_out,
                      ran=set(plan["order"]), supplied=supplied, stain_type=stain_type,
                      save_artifacts=save_artifacts, grandqc_repo=grandqc_repo,
                      grandqc_python=grandqc_python, grandqc_source=grandqc_source, run_set=run_set,
                      bank=bank, norm_method=norm_method, pen_weights=pen_weights, write=write,
                      meta_sources=m1_meta.sources_from_paths(metadata_paths, key=metadata_key),
                      metadata_enabled=metadata_enabled, warnings=warnings)

    # ---- supplied artifacts, decoded before anything expensive ---------------------------------
    thumb, tile_list = _load_supplied(ctx, _warn)

    # Create a fresh dated run under its source-specific slide folder only after preflight.
    ctx.out_dir = output_layout.create_run_dir(base_out, ctx.slide_path) if (write or save_artifacts) else None
    # Attach the slide/run identity to logs for this call and reset it on every exit.
    token = _RUN_ID.set(f"{ctx.out_dir.parent.name}/{ctx.out_dir.name}") if ctx.out_dir is not None else None
    try:
        return _execute(ctx, GCSWSIReader, thumb, tile_list, _warn, t0)
    finally:
        if token is not None:
            _RUN_ID.reset(token)


def _execute(ctx: _RunContext, reader_factory, thumb, tile_list, warn, t0: float) -> dict:
    """Everything past pre-flight: open + M1, stages, then best-effort report publication.

    `reader_factory` is looked up by `run()` at call time (`GCSWSIReader` on the module), which is
    what the suites patch to inject a synthetic slide.
    """
    _warn = warn
    slide_path, plan, supplied, run_set = ctx.slide_path, ctx.plan, ctx.supplied, ctx.run_set
    grandqc_repo, grandqc_source = ctx.grandqc_repo, ctx.grandqc_source
    bank, norm_method, pen_weights = ctx.bank, ctx.norm_method, ctx.pen_weights
    ran, inputs, results = ctx.ran, ctx.inputs, ctx.results

    # Attempt a report for processing failures; filesystem errors can prevent publication.
    # Preflight creates no slide report, but the output parent may already exist.
    # Preserve completed sections and mark unreached work, then propagate RunFailed.
    stage = "m1.localize" if plan["needs_localize"] else "m1.open"
    stage_holder = {"stage": stage}          # the open / M1 helpers report their sub-stages through this
    failure: dict | None = None
    reader = None
    try:
        stage = "initialization"
        if ctx.out_dir is not None:
            # Write running status before processing; final publication records completed or failed.
            _write_status(ctx.out_dir, ctx.slide_id, state="running", started_at=now_stamps()[0],
                          pid=os.getpid(), slide_path=slide_path, components=sorted(run_set),
                          batch_fingerprint=os.environ.get("PATHND_BATCH_FINGERPRINT"))
            started_file = os.environ.get("PATHND_BATCH_RUN_STARTED_FILE")
            if started_file:
                with store.atomic_write(started_file) as tmp:
                    tmp.write_text(json.dumps({"run_dir": str(ctx.out_dir)}), encoding="utf-8")

        reader = reader_factory()
        results.update({"_external_backends": _describe_backends(ctx),
                        "_grandqc_repo": ({"path": grandqc_repo, "source": grandqc_source}
                                          if grandqc_repo else None)})
        # ---- open / localize, only if something needs it -----------------------------------------
        if plan["needs_open"]:
            # An ExitStack rather than nested `with`s: the M2 read may need to close the streamed
            # handle, download the file and reopen it (see `_m2_localize_reason`).
            stack = ExitStack()
            try:
                localized = False
                try:
                    # Inspect acquisition first; rejected tile work must not download the slide.
                    try:
                        local, slide = _open_slide(ctx, reader, stack, stage_holder, False)
                    except Exception:
                        if not plan["needs_localize"] or "://" not in str(slide_path):
                            raise
                        # Some remote formats require a local seekable file even for their header.
                        stack.close()
                        stack = ExitStack()
                        local, slide = _open_slide(ctx, reader, stack, stage_holder, True,
                                                   reason="streamed header unavailable")
                        localized = True
                finally:
                    stage = stage_holder["stage"]
                try:
                    src = _m1_stage(ctx, reader, slide, stage_holder, _warn)
                finally:
                    stage = stage_holder["stage"]
                ctx.stain_type = src["stain_type"]
                bank = bank or src.get("dataset")
                results["_stain_routing"] = _stain_routing(ctx.stain_type, _warn)
                if not localized and plan["needs_localize"] and ctx.checks["mpp"].get("passed"):
                    stack.close()
                    stack = ExitStack()
                    try:
                        local, slide = _open_slide(ctx, reader, stack, stage_holder, True,
                                                   reason="eligible tile work")
                        localized = True
                    finally:
                        stage = stage_holder["stage"]

                # Refuse physically implausible scales. Coarse but plausible slides can still run M2.
                m2_refused = _m2_refusal(ctx.checks) if thumb is None else None
                if m2_refused:
                    stage = "m2"
                    # Record a refused read with its target and the M1 scale reason.
                    ctx.m2_read = {"target_mpp": M2_TARGET_MPP, "error": f"refused: {m2_refused}",
                                   "scale_source": ctx.checks["mpp"].get("scale_source")}
                    _skip_m2(m2_refused, supplied, ran, out=results)
                else:
                    if thumb is None:
                        # Localize remote slides whose selected level exceeds the read cap, then read bands from disk.
                        why = _m2_localize_reason(ctx.info, slide_path, localized)
                        if why:
                            stack.close()
                            stack = ExitStack()
                            try:
                                local, slide = _open_slide(ctx, reader, stack, stage_holder, True, reason=why)
                            finally:
                                stage = stage_holder["stage"]
                        stage = "m2.plane_read"
                        _t = time.monotonic()
                        thumb, ctx.m2_read = reader.read_at_mpp(slide, M2_TARGET_MPP, info=ctx.info)
                        ctx.stage_t["m2.plane_read"] = round(time.monotonic() - _t, 4)
                        if ctx.m2_read is not None:
                            ctx.m2_read["scale_source"] = ctx.checks["mpp"].get("scale_source")
                        if thumb is None:
                            raise RuntimeError(f"could not read the {M2_TARGET_MPP} um/px "
                                               f"plane: {(ctx.m2_read or {}).get('error')}")
                        inputs["thumbnail"] = {"source": "computed",
                                               "mpp": ctx.m2_read["achieved_mpp"],
                                               "dims": list(ctx.m2_read["plane_dims"])}
                    stage = "m2"
                    _run_m2(thumb, ctx.m2_read, ctx.stain_type, supplied, inputs, ran,
                            pen_weights=pen_weights, out=results)
                tissue_mask = results.get("_tissue_mask")
                tissue_error = (results.get("tissue") or {}).get("tissue_error")
                stage = "m3"
                _run_m3(ctx, reader, slide, local, thumb, tissue_mask, tile_list)
                stage = "m4"
                _run_m4(thumb, tissue_mask, ctx.stain_type, bank, norm_method, ran,
                        out=results, tissue_error=tissue_error, skip=m2_refused)
            finally:
                stack.close()
        else:
            # Fully offline: a supplied thumbnail plus supplied masks, no slide touched at all.
            # The metadata lookup still runs (a CSV join needs no slide), so a stain declared in
            # metadata routes these components exactly as it would online.
            stage = "m1.metadata"
            meta, src, resolved_from = _resolve_meta(ctx, _warn)
            ctx.record = build_ingestion_record(src, {}, {},
                                                metadata=m1_meta.to_report(meta["result"], meta),
                                                source_resolved_from=resolved_from)
            ctx.record["decision"] = {"status": "not_checked", "flags": [], "quarantine_reason": None,
                                      "note": "slide not opened (every input was supplied), so the M1 "
                                              "acquisition and integrity checks did not run"}
            ctx.info = {}                    # no slide: no acquisition facts, no M1 checks (`checks` stays None)
            ctx.stain_type = src["stain_type"]
            bank = bank or src.get("dataset")
            results["_stain_routing"] = _stain_routing(ctx.stain_type, _warn)
            stage = "m2"
            _run_m2(thumb, None, ctx.stain_type, supplied, inputs, ran,
                    pen_weights=pen_weights, out=results)
            # Use the same M3 helper for slide-backed and supplied-image runs.
            stage = "m3"
            _run_m3(ctx, reader, None, None, thumb, results.get("_tissue_mask"), tile_list)
            stage = "m4"
            _run_m4(thumb, results.get("_tissue_mask"), ctx.stain_type, bank, norm_method, ran,
                    out=results, tissue_error=(results.get("tissue") or {}).get("tissue_error"))

    except (Exception, KeyboardInterrupt) as exc:  # preserve interrupted work and final status
        failure = {"stage": stage, "type": type(exc).__name__, "message": str(exc),
                   "traceback": traceback.format_exc()}

    report, report_path = _publish(ctx, thumb, failure, t0)
    # Remove internal tissue and degradation fields from the public return value.
    return {"report": report, "report_path": report_path, "out_dir": ctx.out_dir, "plan": plan,
            "checks": ctx.checks, "record": ctx.record, "read": ctx.m2_read, "thumbnail": thumb,
            "outputs": ctx.outputs, **{k: v for k, v in results.items() if not str(k).startswith("_")}}


def _load_supplied(ctx: _RunContext, warn) -> tuple:
    """Decode every supplied artifact BEFORE anything expensive; returns (thumbnail, tile_list).

    An unreadable file refuses here, with nothing written and no download paid. Masks are decoded
    too, then loaded again by `_run_m2` once the plane exists and their size can be checked (small
    files; the second read is the price of failing early).
    """
    supplied, inputs = ctx.supplied, ctx.inputs
    thumb = tile_list = None
    if "thumbnail" in supplied:
        got = store.load_image(supplied["thumbnail"], max_pixels=cfg("m2.read.max_plane_px", 64 * 1024 * 1024))
        if got["error"]:
            raise ValueError(f"--thumbnail: {got['error']}")
        # PNG/NPY inputs do not provide MPP. Record the configured analysis scale as an assumption.
        assumed = spec.ARTIFACTS["thumbnail"]["mpp"]
        thumb = got["image"]
        _validate_plane_size(thumb.width, thumb.height)
        inputs["thumbnail"] = dict(got["provenance"], mpp=assumed,
                                   mpp_source=f"assumed: a supplied image carries no MPP; "
                                              f"ARTIFACTS.thumbnail.mpp ({assumed}) is taken on trust")
    if "tile_list" in supplied:
        got = store.load_json(supplied["tile_list"])
        if got["error"]:
            raise ValueError(f"--tile_list: {got['error']}")
        # Validate the parsed tile-list structure before any slide I/O.
        tile_list, declared = _parse_tile_list(got["data"], warn)
        inputs["tile_list"] = dict(got["provenance"], n=len(tile_list), **declared)
    for name in ("pen_mask", "tissue_mask", "fold_mask"):
        if name in supplied:
            _supplied_mask(name, supplied, _hw(thumb), {})
    return thumb, tile_list


def _describe_backends(ctx: _RunContext) -> dict:
    """Provenance of the external backends this run will use; a description failure is recorded,
    never raised -- the backend itself reports when it runs."""
    from pathnd_qc.external.paths import describe_pen, describe_grandqc
    run_set, pen_weights, grandqc_repo, grandqc_python = (ctx.run_set, ctx.pen_weights,
                                                          ctx.grandqc_repo, ctx.grandqc_python)
    out: dict = {}
    for name, selected, describe in (
        ("pen", "pen_detection" in run_set, lambda: describe_pen(pen_weights or m2_pen.DEFAULT_WEIGHTS)),
        ("grandqc", "tile_artifacts" in run_set and bool(grandqc_repo),
         lambda: describe_grandqc(grandqc_repo, grandqc_python)),
    ):
        if selected:
            try:
                out[name] = describe()
            except (OSError, ValueError, TypeError) as exc:
                out[name] = {"error": str(exc)}
    return out


def _resolve_meta(ctx: _RunContext, warn) -> tuple:
    """Join metadata CSVs on the slide key for both slide-backed and supplied-image runs."""
    meta = m1_meta.lookup(ctx.slide_path, sources=ctx.meta_sources, enabled=ctx.metadata_enabled)
    for problem in (meta.get("index_errors") or []):
        warn(f"metadata source problem: {problem.get('error', problem)}")
    if meta.get("error_type"):
        warn(f"metadata lookup failed: {meta.get('error')}")
    src, resolved_from = m1_meta.merge_source(meta["result"], ctx.slide_path, stain_type=ctx.stain_type)
    if src.get("dataset") is None and ctx.bank:
        src["dataset"], resolved_from["dataset"] = ctx.bank, "cli"
    ctx.results["metadata"] = meta
    return meta, src, resolved_from


def _m1_stage(ctx: _RunContext, reader, slide, stage_holder: dict, warn) -> dict:
    """M1 -- always: slide info, the checks, metadata, the record. Returns the resolved `source`."""
    stage_holder["stage"] = "m1.info"
    ctx.info = reader.get_slide_info(slide)
    stage_holder["stage"] = "m1.checks"
    _t = time.monotonic()
    ctx.checks = {"magnification": check_magnification(ctx.info), "mpp": check_mpp(ctx.info),
                  "integrity": check_integrity(slide, ctx.info)}
    ctx.stage_t["m1.checks"] = round(time.monotonic() - _t, 4)
    stage_holder["stage"] = "m1.metadata"
    meta, src, resolved_from = _resolve_meta(ctx, warn)
    # Preserve raw acquisition fields in the record; downstream reads use the effective scale.
    ctx.record = build_ingestion_record(src, ctx.info, ctx.checks,
                                        metadata=m1_meta.to_report(meta["result"], meta),
                                        source_resolved_from=resolved_from)
    ctx.record["decision"] = decide(ctx.record)
    ctx.info = apply_scale(ctx.info, ctx.checks["mpp"])
    if str(ctx.info.get("mpp_source") or "").startswith("derived"):
        warn(f"level-0 scale {ctx.info['mpp_source']}; M2, M3 and every um-defined gate ran on it")
    return src


def _open_slide(ctx: _RunContext, reader, stack: ExitStack, stage_holder: dict, do_localize: bool,
                reason: str | None = None):
    """Enter (localize?) + open on `stack`; returns (local_path, slide). Raises naming the step."""
    if do_localize:
        stage_holder["stage"] = "m1.localize"
        _t = time.monotonic()
        local = stack.enter_context(reader.localize(ctx.slide_path))
        # Copy localization details before testing success so download failures retain their cause.
        ctx.stage_t["m1.localize"] = round(ctx.stage_t.get("m1.localize", 0.0) + time.monotonic() - _t, 4)
        ctx.localize_info = dict(reader.last_localize or {})
        if reason:
            ctx.localize_info["reason"] = reason
        if local is None:
            raise RuntimeError(f"could not localize {ctx.slide_path}: "
                               f"{ctx.localize_info.get('error') or 'download failed'}")
    else:
        local = ctx.slide_path
    stage_holder["stage"] = "m1.open"
    _t = time.monotonic()
    slide = stack.enter_context(reader.slide(local))
    if slide is None:
        raise RuntimeError(f"could not open {ctx.slide_path}")
    ctx.stage_t["m1.open_and_info"] = round(time.monotonic() - _t, 4)
    return local, slide


def _publish(ctx: _RunContext, thumb, failure: dict | None, t0: float) -> tuple:
    """Save computed artifacts, assemble the report, and write final status.

    Usable partial outputs are retained after a stage failure. Publication errors are
    recorded alongside the original failure. Returns (report, report_path), or raises
    RunFailed with the report and failure details.
    """
    out_dir, slide_id, slide_path = ctx.out_dir, ctx.slide_id, ctx.slide_path
    if ctx.save_artifacts:
        stage = "save_artifacts"
        save_errors: list = []
        try:
            ctx.outputs.update(_save_artifacts(ctx.results, thumb, out_dir, slide_id, ctx.ran,
                                               errors=save_errors))
        except (Exception, KeyboardInterrupt) as exc:
            save_failure = {"stage": stage, "type": type(exc).__name__, "message": str(exc),
                            "traceback": traceback.format_exc()}
            failure = save_failure if failure is None else dict(failure, save_error=save_failure)
        if save_errors:
            save_failure = dict(save_errors[0], artifacts=save_errors)
            failure = save_failure if failure is None else dict(failure, save_error=save_failure)

    report, report_path = None, None
    for attempt in range(2):
        try:
            stage = "assemble"
            report = _assemble(ctx, total_s=time.monotonic() - t0, failure=failure)
            execution = report["provenance"]["execution"]
            if failure is None and not execution["complete"]:
                failure = {"stage": "completion", "type": "IncompleteRun",
                           "message": "; ".join(execution["reasons"])}
                report["error"] = failure
            stage = "write_report"
            report_path = write_report(report, str(out_dir)) if ctx.write else None
            stage = "write_status"
            _finish_status(out_dir, slide_id, failure, report_path, slide_path=slide_path)
            break
        except (Exception, KeyboardInterrupt) as exc:
            write_failure = {"stage": stage, "type": type(exc).__name__, "message": str(exc),
                             "traceback": traceback.format_exc()}
            failure = write_failure if failure is None else dict(failure, write_error=write_failure)
            # A first interruption during publication needs its own failure report. Retry once;
            # an actual filesystem failure is not made recoverable by repeatedly writing to it.
            if isinstance(exc, KeyboardInterrupt) and attempt == 0:
                continue
            if report is None:
                report = {"slide_id": slide_id, "slide_path": slide_path, "error": failure,
                          "provenance": dict(ctx.run_provenance)}
            else:
                report["error"] = failure
            try:
                _finish_status(out_dir, slide_id, failure, report_path, slide_path=slide_path)
            except (Exception, KeyboardInterrupt) as status_exc:
                # Write status last and attach any status-write failure to the run failure.
                failure = dict(failure, status_error={"type": type(status_exc).__name__,
                                                      "message": str(status_exc)})
                report["error"] = failure
            raise RunFailed(failure, report, report_path) from exc
    result_browser.write_run_index(report, report_path, out_dir,
                                   None if os.environ.get("PATHND_BATCH_OUT_DIR") else ctx.output_root)
    if failure is not None:
        raise RunFailed(failure, report, report_path)
    return report, report_path


def _write_status(out_dir, slide_id: str, **fields) -> None:
    """`<run folder>/<slide_id>_status.json`, written atomically; never allowed to fail a run."""
    try:
        store.save_json(dict(fields), Path(out_dir) / f"{slide_id}_status.json")
    except Exception as exc:  # noqa: BLE001 -- a status marker must not mask the run's own outcome
        get_logger(__name__).warning("could not write the status file: %s", exc)


def _finish_status(out_dir, slide_id: str, failure: dict | None, report_path, *, slide_path=None) -> None:
    if out_dir is None:
        return
    fields = {"state": "failed" if failure else "completed", "finished_at": now_stamps()[0],
              "report": os.path.basename(str(report_path)) if report_path else None}
    if failure:
        fields.update(stage=failure.get("stage"), type=failure.get("type"), message=failure.get("message"))
    loaded = store.load_json(Path(out_dir) / f"{slide_id}_status.json")
    prior = loaded.get("data")
    prior_error = loaded.get("error")
    if not isinstance(prior, dict):
        prior_error = prior_error or "status must be a JSON object"
        prior = {}
    elif not isinstance(prior.get("slide_path"), str) or not prior["slide_path"].strip():
        prior_error = prior_error or "status needs a non-empty slide_path"
    valid_identity = isinstance(prior.get("slide_path"), str) and bool(prior["slide_path"].strip())
    if slide_path is None and not valid_identity and report_path:
        saved = store.load_json(report_path).get("data")
        slide_path = saved.get("slide_path") if isinstance(saved, dict) else None
    if slide_path is not None:
        fields["slide_path"] = slide_path
    if prior_error:
        get_logger(__name__).warning("could not read prior run status: %s", prior_error)
        fields["prior_status_error"] = prior_error
    _write_status(out_dir, slide_id, **{**prior, **fields})


def _validate_plane_size(width, height):
    limit = cfg("m2.read.max_plane_px", 64 * 1024 * 1024)
    if width * height > limit:
        raise ValueError(f"analysis image {width}x{height} exceeds m2.read.max_plane_px={limit}; "
                         "increase the explicit resource budget for this slide")


def _m2_localize_reason(info: dict, slide_path: str, already_localized: bool) -> str | None:
    """Return the reason M2 needs a local copy, or None.

    Remote slides are localized when the selected pyramid level exceeds
    `m2.read.max_read_px`, allowing banded reads from disk. The decision uses header
    metadata without reading pixels. Local files need no download.
    """
    if already_localized or "://" not in str(slide_path):
        return None
    plan = resolve_mpp_level(info, M2_TARGET_MPP)
    if plan["error"] or plan["level"] is None:
        return None
    lw, lh = info["level_dimensions"][plan["level"]]
    cap = m1_wsi.M2_MAX_READ_PX
    if lw * lh <= cap:
        return None
    return (f"M2 reads level {plan['level']} ({lw}x{lh} = {lw * lh:,} px), over the "
            f"{int(cap):,} px cap (m2.read.max_read_px): downloaded before the banded read rather "
            f"than streamed from the bucket")


def _m2_refusal(checks: dict | None) -> str | None:
    """Why the M2 plane must NOT be read, or None. Only M1's `implausible` verdict refuses --
    a slide that merely failed the coarseness bound has a real scale and is still read."""
    mpp_check = (checks or {}).get("mpp") or {}
    if mpp_check.get("implausible"):
        return f"M2 plane read refused, M1 mpp check: {mpp_check.get('reason')}"
    return None


def _skip_m2(why: str, supplied: dict, ran: set, out: dict) -> None:
    """Every M2 section as a recorded skip naming the refusal; supplied masks are noted as unused."""
    for key, comp in (("pen", "pen_detection"), ("tissue", "tissue_segmentation"),
                      ("folds", "fold_detection"), ("staining", "staining_quality"),
                      ("focus", "focus")):
        art = _SUPPLIED_FOR.get(key)
        if comp in ran:
            out[key] = _skip(why)
        elif art and art in supplied:
            out[key] = _skip(f"{_supplied_reason(art)}, unused: {why}")
        else:
            out[key] = _skip(_not_selected(comp))
    out["_tissue_mask"] = None


def _tile_int(v):
    """An integer coordinate: int, or a float that IS an integer (2.0 -> 2). Never a bool."""
    if isinstance(v, bool):
        return None
    if isinstance(v, int):
        return v
    if isinstance(v, float) and v.is_integer():
        return int(v)
    return None


_TILE_LIST_SHAPE = ("--tile_list: expected a non-empty JSON array of tiles, or an object "
                    "{plane_mpp, plane_dims: [w, h], tiles: [...]} (what tile_selection writes); each "
                    "tile is a dict with integer x/y/w/h (x/y >= 0, w/h > 0) and optional integer "
                    "col/row")


def _parse_tile_list(data, warn) -> tuple[list, dict]:
    """Validate a supplied tile list and return (tiles, declared plane).

    Coordinates must be integers. Duplicate x/y/w/h entries are removed and counted in
    a warning. Plane metadata, when present, is checked against the resolved tile plane
    by `_run_m3`; tile geometry is also checked against its bounds. Bare arrays supply
    geometry without a declared plane. Invalid structures raise ValueError.
    """
    declared = {"plane_mpp": None, "plane_dims": None}
    tiles = data
    if isinstance(data, dict):
        tiles = data.get("tiles")
        dims = data.get("plane_dims")
        if (not isinstance(dims, (list, tuple)) or len(dims) != 2
                or any(_tile_int(d) is None or _tile_int(d) <= 0 for d in dims)):
            raise ValueError(_TILE_LIST_SHAPE)
        declared["plane_dims"] = [int(dims[0]), int(dims[1])]
        mpp = data.get("plane_mpp")
        if mpp is not None and (isinstance(mpp, bool) or not isinstance(mpp, (int, float))):
            raise ValueError(f"--tile_list: plane_mpp must be a number, got {type(mpp).__name__}")
        if mpp is not None and (not math.isfinite(mpp) or mpp <= 0):
            raise ValueError("--tile_list: plane_mpp must be finite and positive")
        declared["plane_mpp"] = (float(mpp) if isinstance(mpp, (int, float)) and not isinstance(mpp, bool)
                                 else None)
    if not isinstance(tiles, list) or not tiles:
        raise ValueError(_TILE_LIST_SHAPE)
    clean, seen, dupes = [], set(), 0
    for t in tiles:
        if not isinstance(t, dict) or not {"x", "y", "w", "h"} <= set(t):
            raise ValueError(_TILE_LIST_SHAPE)
        vals = {k: _tile_int(t[k]) for k in ("x", "y", "w", "h")}
        if (any(v is None for v in vals.values()) or vals["x"] < 0 or vals["y"] < 0
                or vals["w"] <= 0 or vals["h"] <= 0):
            raise ValueError(_TILE_LIST_SHAPE)
        if vals["w"] > m3_tiles.TILE_PX or vals["h"] > m3_tiles.TILE_PX:
            raise ValueError(f"--tile_list: tile w/h must not exceed tile_px={m3_tiles.TILE_PX}; "
                             "split large regions into tiles")
        for k in ("col", "row"):
            if k in t and _tile_int(t[k]) is None:
                raise ValueError(_TILE_LIST_SHAPE)
        key = (vals["x"], vals["y"], vals["w"], vals["h"])
        if key in seen:
            dupes += 1
            continue
        seen.add(key)
        clean.append(dict(t, **vals, **{k: _tile_int(t[k]) for k in ("col", "row") if k in t}))
    if dupes:
        warn(f"--tile_list: {dupes} duplicate tile(s) removed (same x/y/w/h); "
             f"{len(clean)} distinct tiles kept")
    return clean, declared


def _stain_routing(stain_type, warn) -> dict:
    """Record stain routing and warn when a supplied stain matches no known spelling.

    The stain string selects tissue and fold algorithms and normalization references.
    Unrecognized metadata spellings produce a warning rather than refusing the run.
    """
    norm = (stain_type or "").strip().lower()
    hirano = norm in m2_tissue.HIRANO_STAINS
    method = m2_tissue.route_by_stain_type(stain_type)
    fold_method = "d" if m2_folds._uses_d_path(stain_type) else "stain2"
    vocab = (set(m2_tissue.HIRANO_STAINS) | set(m2_folds.D_PATH_STAINS) | set(m4_norm.STAIN_ALIASES)
             | {str(k).split("/")[0].strip().lower() for k in (cfg("m4.reference", {}) or {})})
    recognised = None if stain_type is None else norm in vocab
    if recognised is False:
        warn(f"stain {stain_type!r} matched no configured stain vocabulary "
             f"(m2.tissue.hirano_stains, m2.folds.d_path_stains, m4.stain_aliases, m4.reference keys); "
             f"tissue used {method!r}, folds used {fold_method!r}, and M4 will find no "
             f"reference -- a typo?")
    return {"stain_type": stain_type, "recognised": recognised, "hirano": hirano,
            "tissue_method": method, "fold_route": fold_method,
            "fold_fline_enabled": m2_folds.FLINE_ENABLED,
            "vocabulary": sorted(vocab)}


def _run_m2(thumb, m2_read, stain_type, supplied, inputs, ran,
            pen_weights=None, out: dict | None = None) -> dict:
    """Run M2 components in order, storing each result as it finishes.

    Tissue segmentation precedes fold detection, followed by pen detection. Supplied
    masks take precedence over computed masks and are not modified. When both masks
    are computed, folds take precedence over pen at overlapping pixels. Staining and
    focus exclude the union of available fold and pen masks. Completed results remain
    available if a later component fails.
    """
    out = {} if out is None else out
    # Inspect each component error and record its downstream effects in provenance.degraded.
    degraded = out.setdefault("_degraded", {})

    # tissue
    tissue_error = None
    if "tissue_segmentation" in ran:
        out["tissue"] = m2_tissue.compute_tissue_mask(thumb, stain_type=stain_type)
        tissue_mask = out["tissue"].get("tissue_mask")
        tissue_error = out["tissue"].get("tissue_error")
        # `inputs` says what the downstream components actually got: a computed mask, or nothing.
        inputs["tissue_mask"] = ({"source": "computed"} if tissue_mask is not None
                                 else {"source": "failed", "error": tissue_error})
    elif "tissue_mask" in supplied:
        tissue_mask = _supplied_mask("tissue_mask", supplied, _hw(thumb), inputs)
        out["tissue"] = _skip(_supplied_reason("tissue_mask"))
    else:
        tissue_mask = None
        out["tissue"] = _skip(_not_selected("tissue_segmentation"))
    out["_tissue_mask"] = tissue_mask
    # Propagate tissue-segmentation failure to dependent components instead of allowing
    # implicit resegmentation or measurements without tissue support.
    no_tissue = _skip(f"tissue mask failed -> {tissue_error}") if tissue_error else None

    # folds -- on the tissue alone
    fold_mask, fold_supplied, fold_state = None, False, None
    if "fold_detection" in ran:
        if no_tissue:
            out["folds"], fold_state = dict(no_tissue), "fold detection skipped: tissue mask failed"
        else:
            out["folds"] = m2_folds.detect_folds(
                thumb, tissue_mask=tissue_mask, stain_type=stain_type,
                thumb_mpp=(m2_read or {}).get("achieved_mpp", M2_TARGET_MPP))
            fold_mask = out["folds"].get("fold_mask")
            if out["folds"].get("fold_error"):
                fold_state = f"fold detection failed ({out['folds']['fold_error']})"
                degraded["fold_detection"] = (f"folds failed; staining/focus ran with NO fold "
                                              f"exclusion: {out['folds']['fold_error']}")
            elif out["folds"].get("fline_error"):
                degraded["fold_detection"] = (
                    f"line-fold detection failed; ConnSoftT mask used without F_line: "
                    f"{out['folds']['fline_error']}")
    elif "fold_mask" in supplied:
        fold_mask = _supplied_mask("fold_mask", supplied, _hw(thumb), inputs)
        out["folds"] = _skip(_supplied_reason("fold_mask"))
        fold_supplied = True
    else:
        out["folds"] = _skip(_not_selected("fold_detection"))
        fold_state = "fold detection not run and no --fold_mask"

    # pen -- AFTER folds, so a computed pen mask can yield to them
    pen_supplied = False
    if "pen_detection" in ran:
        # --pen_weights overrides m2.pen.weights_path; the module falls back to config when None.
        out["pen"] = (m2_pen.detect_pen(thumb, weights_path=pen_weights, fold_mask=fold_mask) if pen_weights
                      else m2_pen.detect_pen(thumb, fold_mask=fold_mask))
        pen_mask = out["pen"].get("pen_mask")
        if pen_mask is not None and fold_mask is None and fold_state:
            out["pen"]["note"] = f"no fold mask ({fold_state}); pen mask used as is"
        if out["pen"].get("pen_error"):
            if "pen_mask" in supplied:
                # "The computed value wins" only when it EXISTS; a failed computation falls back
                # to the file the caller supplied, and says so.
                pen_mask = _supplied_mask("pen_mask", supplied, _hw(thumb), inputs)
                pen_supplied = True
                out["pen"]["note"] = "computed pen failed; the supplied --pen_mask was used instead"
                degraded["pen_detection"] = (f"computed pen failed ({out['pen']['pen_error']}); "
                                             f"the supplied --pen_mask was used")
            else:
                degraded["pen_detection"] = (f"pen failed; staining/focus ran with NO pen "
                                             f"exclusion: {out['pen']['pen_error']}")
    elif "pen_mask" in supplied:
        pen_mask = _supplied_mask("pen_mask", supplied, _hw(thumb), inputs)
        out["pen"] = _skip(_supplied_reason("pen_mask"))
        pen_supplied = True
    else:
        pen_mask = None
        out["pen"] = _skip(_not_selected("pen_detection"))

    # a SUPPLIED pen takes precedence: the COMPUTED fold yields to it
    if (pen_supplied and pen_mask is not None and fold_mask is not None and not fold_supplied
            and not out["folds"].get("fold_error")):
        m2_folds.subtract_pen(out["folds"], pen_mask)
        fold_mask = out["folds"]["fold_mask"]

    if "staining_quality" in ran:
        out["staining"] = dict(no_tissue) if no_tissue else m2_staining.compute_staining_metrics(
            thumb, tissue_mask=tissue_mask, fold_mask=fold_mask, pen_mask=pen_mask,
            stain_type=stain_type)
    else:
        out["staining"] = _skip(_not_selected("staining_quality"))

    if "focus" in ran:
        out["focus"] = dict(no_tissue) if no_tissue else m2_focus.compute_focus_score(
            thumb, tissue_mask=tissue_mask, fold_mask=fold_mask, pen_mask=pen_mask,
            stain_type=stain_type)
    else:
        out["focus"] = _skip(_not_selected("focus"))

    return out


def _run_m4(thumb, tissue_mask, stain_type, bank, norm_method, ran,
            out: dict | None = None, tissue_error: str | None = None,
            skip: str | None = None) -> dict:
    """Run M4 normalization after M3 using the analysis image and tissue mask.

    An acquisition refusal passed as skip also prevents normalization and supplies
    its report reason.
    """
    out = {} if out is None else out
    if "stain_normalization" not in ran:
        out["stain_norm"] = _skip(_not_selected("stain_normalization"))
        return out
    if skip:
        out["stain_norm"] = _skip(skip)
        return out
    method = norm_method or M4_METHOD
    if tissue_error:
        # Without tissue support, report why normalization cannot run rather than normalizing glass.
        out["stain_norm"] = _skip(f"tissue mask failed -> {tissue_error}")
        return out
    ref = m4_norm.load_reference(stain_type, method=method, bank=bank)
    if ref["error"]:
        out["stain_norm"] = {"result": None, "params": dict(ref["params"], method=method),
                             "runtime_s": ref.get("runtime_s", 0.0),
                             "error": f"no usable reference: {ref['error']}"}
        out["stain_norm"]["error_type"] = error_kind(ref["error"], ref.get("error_type"))
    else:
        out["stain_norm"] = m4_norm.normalize_slide(thumb, ref["result"], method=method,
                                                    tissue_mask=tissue_mask, stain_type=stain_type)
        out["stain_norm"]["params"].update(ref["params"])
    return out


def _m3_gate_from_m1(checks: dict | None, info: dict) -> dict:
    """Use M1's MPP check to decide whether M3 can run.

    Accepted slides are resampled to the tile plane using the tolerance derived from
    M1's bound. Rejected slides retain M1's reason in the M3 skip; M2 and M4 can run
    at their analysis resolution when the scale is plausible.
    """
    if checks is None:
        # A supplied-image run has no M1 check because it does not open the slide.
        return {"ok": None, "status": "not_evaluated", "gate": "m1.checks.mpp",
                "level0_mpp": slide_mpp(info or {}),
                "reason": "not evaluated: slide not opened (every input was supplied), so M1's "
                          "checks did not run"}
    mpp_check = checks.get("mpp") or {}
    ok = bool(mpp_check.get("passed"))
    return {"ok": ok, "status": "ok" if ok else "rejected", "gate": "m1.checks.mpp",
            "level0_mpp": slide_mpp(info),
            "reason": None if ok else f"M1 mpp check failed: {mpp_check.get('reason')}"}


def _run_m3(ctx: _RunContext, reader, slide, local, thumb, tissue_mask, tile_list,
            out: dict | None = None) -> dict:
    """Run tile selection, tile metrics, then artifact detection.

    Results are stored incrementally in `out` or `ctx.results`. Artifact measurements
    remain separate from tile metrics. Supplied-image runs reach this helper only
    when the selected work needs no slide handle.
    """
    out = ctx.results if out is None else out
    info = ctx.info if ctx.info is not None else {}
    checks, inputs, ran, stage_t = ctx.checks, ctx.inputs, ctx.ran, ctx.stage_t
    stain_type, grandqc_repo, grandqc_python = ctx.stain_type, ctx.grandqc_repo, ctx.grandqc_python
    out_dir, slide_id, outputs, save_artifacts = ctx.out_dir, ctx.slide_id, ctx.outputs, ctx.save_artifacts
    requested = {"tile_selection", "tile_metrics", "tile_artifacts"} & ran
    def _skip_rest(why):
        out["tiles"] = _skip(why)
        if "artifacts" not in out:
            out["artifacts"] = _skip(why)
        return out

    if not requested:
        # No requested M3 work means no MPP gate decision.
        why = "no M3 component requested"
        out["m3_gate"] = {"ok": None, "status": "skipped", "gate": None,
                          "level0_mpp": slide_mpp(info or {}), "reason": why}
        return _skip_rest(why)
    out["m3_gate"] = _m3_gate_from_m1(checks, info)
    if out["m3_gate"]["ok"] is False:
        return _skip_rest(out["m3_gate"]["reason"])
    if out["m3_gate"]["ok"] is None:
        # Without an open slide, record that the MPP gate cannot be evaluated.
        return _skip_rest(f"{sorted(requested)} need the slide, which was not opened")
    if tissue_mask is None:
        # Skip tile selection with an explicit reason when its tissue mask is unavailable.
        why = ("tissue mask unavailable: "
               + str((out.get("tissue") or {}).get("tissue_error") or "not computed and not supplied"))
        out["m3_gate"].update(ok=False, status="skipped", reason=why)
        return _skip_rest(why)

    # Check resolution errors before using plane dimensions.
    plan = resolve_mpp_level(info, m3_tiles.TILE_TARGET_MPP, tol=m3_tiles.M3_MPP_TOL_REL)
    if plan["error"] or not plan["plane_dims"]:
        reason = f"cannot resolve the {m3_tiles.TILE_TARGET_MPP} um/px tile plane: {plan['error']}"
        out["m3_gate"].update(ok=False, status="rejected", reason=reason)
        return _skip_rest(reason)
    plane_dims = plan["plane_dims"]
    out["plane_dims"] = plane_dims
    out["m3_gate"]["tile_plane"] = {k: plan[k] for k in ("level", "source_mpp", "achieved_mpp",
                                                          "resample_ratio", "direction", "tol")}
    out["m3_gate"]["tile_plane"]["scale_source"] = (checks.get("mpp") or {}).get("scale_source")
    # After opening the slide, validate both the supplied tile list’s declared plane and its geometry.
    if tile_list is not None and "tile_selection" not in ran:
        pw, ph = plane_dims
        declared = (inputs.get("tile_list") or {}).get("plane_dims")
        why = None
        declared_mpp = inputs["tile_list"].get("plane_mpp")
        if declared_mpp is not None and not math.isclose(declared_mpp, m3_tiles.TILE_TARGET_MPP):
            why = (f"supplied --tile_list uses {declared_mpp} um/px; "
                   f"this run uses {m3_tiles.TILE_TARGET_MPP} um/px")
        elif declared is not None and list(declared) != [pw, ph]:
            why = (f"supplied --tile_list was selected on a "
                   f"{inputs['tile_list'].get('plane_mpp') or '?'} um/px plane of {list(declared)} px; "
                   f"this slide's {m3_tiles.TILE_TARGET_MPP} um/px plane is {[pw, ph]} px "
                   f"(a different slide, or a different m3.read.tile_target_mpp?)")
        else:
            outside = sum(1 for t in tile_list if t["x"] + t["w"] > pw or t["y"] + t["h"] > ph)
            if outside:
                why = (f"supplied --tile_list does not fit the {m3_tiles.TILE_TARGET_MPP} um/px "
                       f"plane {[pw, ph]}: {outside} of {len(tile_list)} tiles lie outside it "
                       f"(a different slide, or a different plane?)")
        if why:
            inputs["tile_list"] = dict(inputs.get("tile_list") or {}, error=why)
            out["tile_list"] = None
            return _skip_rest(why)

    # Select tiles from the tissue mask.
    if "tile_selection" in ran:
        _t = time.monotonic(); tile_list = select_tissue_tiles(tissue_mask, plane_dims)
        stage_t["m3.tile_selection"] = round(time.monotonic() - _t, 4)
        inputs["tile_list"] = {"source": "computed", "n": len(tile_list)}
    out["tile_list"] = tile_list

    # tile_metrics.py — the tile-plane tissue mask is assembled AS THE LOOP RUNS, never buffered.
    if "tile_metrics" not in ran:
        out["tiles"] = _skip(_not_selected("tile_metrics"))
        out["overlay"] = None
    elif not tile_list:
        # An empty tile list produces an explicit skip and no fine mask.
        out["tiles"] = _skip("no tissue tiles selected (empty tissue mask?)")
        out["overlay"] = None
    else:
        writer, mask_error = None, None
        if save_artifacts:
            try:
                writer = store.TiledMaskWriter(plane_dims, mpp=m3_tiles.TILE_TARGET_MPP)
            except (ValueError, MemoryError) as exc:
                mask_error = f"{type(exc).__name__}: {exc}"
        out["tiles"] = m3_tiles.compute_tile_metrics(reader, slide, tissue_mask, tile_list,
                                                     plane_dims, info=info, stain_type=stain_type,
                                                     mask_writer=writer)
        if mask_error:
            out["tiles"].update(mask_write_error=mask_error, mask_complete=False)
        if (writer is not None and not out["tiles"].get("tile_error")
                and not out["tiles"].get("mask_write_error")):
            _t = time.monotonic()
            try:
                outputs["tissue_mask_20x"] = writer.write(
                    output_layout.artifact_path(out_dir, "tissue_mask_20x", slide_id))
            except Exception as exc:  # preserve measured records if artifact publication fails
                out["tiles"].update(mask_write_error=f"{type(exc).__name__}: {exc}", mask_complete=False)
            stage_t["m3.mask_write"] = round(time.monotonic() - _t, 4)
        if out["tiles"].get("mask_write_error"):
            out.setdefault("_degraded", {})["tissue_mask_20x"] = out["tiles"]["mask_write_error"]
        if out["tiles"].get("tile_error"):
            out["overlay"] = None          # a "heatmap" of a failed pass is the bare thumbnail
        else:
            _t = time.monotonic()
            out["overlay"] = m3_tiles.generate_blur_overlay(thumb, out["tiles"], plane_dims)
            stage_t["m3.blur_overlay"] = round(time.monotonic() - _t, 4)

    # artifacts.py — needs only tile GEOMETRY, so the tile list is enough; it does NOT need metrics.
    if "tile_artifacts" in ran:
        out["artifacts"] = m3_artifacts.detect_slide_artifacts(
            local, tile_list or [], plane_dims, grandqc_repo=grandqc_repo, python=grandqc_python)
        # The class map is already in hand -- render it rather than discard it. Guarded: a failed
        # backend returns no map, and that must not take the run down.
        amap = (out["artifacts"] or {}).get("artifact_map")
        if save_artifacts and amap and amap.get("class_map") is not None:
            _t = time.monotonic()
            try:
                out["artifact_overlay"] = m3_artifacts.generate_artifact_overlay(
                    thumb, amap, classes=tuple(cfg("m3.artifacts.classes", ("fold", "pen", "bubble"))))
            except Exception as exc:  # noqa: BLE001 -- overlay failure is recorded as a diagnostic degradation
            # Include a failed overlay in the report without discarding measurements.
                out.setdefault("_degraded", {})["artifact_overlay"] = (
                    f"artifact overlay failed and was not written: {type(exc).__name__}: {exc}")
            stage_t["m3.artifact_overlay"] = round(time.monotonic() - _t, 4)
    elif "tile_artifacts" not in ran:
        out["artifacts"] = _skip(_not_selected("tile_artifacts"))
    return out


def _save_artifacts(results, thumb, out_dir, slide_id, ran, *, errors: list | None = None) -> dict:
    """Save generated outputs and record their provenance; do not copy supplied input files."""
    written: dict = {}
    out_dir = Path(out_dir)

    def save(name, writer, value):
        path = output_layout.artifact_path(out_dir, name, slide_id)
        try:
            written[name] = writer(value, path)
        except (Exception, KeyboardInterrupt) as exc:  # preserve other independently saved outputs
            if errors is None:
                raise
            errors.append({"stage": "save_artifacts", "artifact": name, "path": str(path),
                           "type": type(exc).__name__, "message": str(exc),
                           "traceback": traceback.format_exc()})

    def _mask_of(section, key):
        val = (results.get(section) or {}).get(key)
        return val if isinstance(val, np.ndarray) else None

    for section, key, name in (("tissue", "tissue_mask", "tissue_mask"),
                               ("folds", "fold_mask", "fold_mask"),
                               ("pen", "pen_mask", "pen_mask")):
        m = _mask_of(section, key)
        if m is not None:
            save(name, store.save_mask_png, m)
    if results.get("tile_list") and "tile_selection" in ran:
        # Save tile-plane metadata alongside the coordinates.
        doc = {"plane_mpp": m3_tiles.TILE_TARGET_MPP,
               "plane_dims": list(results["plane_dims"]) if results.get("plane_dims") else None,
               "tiles": results["tile_list"]}
        save("tile_list", store.save_json, doc)
    tiles = results.get("tiles") or {}
    if tiles.get("tiles"):
        save("tile_records", store.save_json, tiles["tiles"])
    norm = (results.get("stain_norm") or {}).get("result")
    if norm is not None:
        def save_normalized(value, path):
            from PIL import Image
            return store.save_image_png(Image.fromarray(np.asarray(value, dtype=np.uint8)), path)
        save("normalized_image", save_normalized, norm)
    overlay = results.get("overlay")
    if overlay is not None:
        save("blur_overlay", store.save_image_png, overlay)
    art_overlay = results.get("artifact_overlay")
    if art_overlay is not None:
        save("artifact_overlay", store.save_image_png, art_overlay)
    return written


def _assemble(ctx: _RunContext, total_s: float, failure: dict | None = None) -> dict:
    """Assemble a report with results and explicit reasons for skipped components.

    Failed runs retain the same section structure. `components_run` lists components
    that produced results, and the top-level error identifies the failure stage.
    Successful reports contain error=None.
    """
    slide_id, slide_path, stain_type = ctx.slide_id, ctx.slide_path, ctx.stain_type
    record, localize_info, m2_read = ctx.record, ctx.localize_info, ctx.m2_read
    ran, plan, inputs, outputs, stage_t = ctx.ran, ctx.plan, ctx.inputs, ctx.outputs, ctx.stage_t
    supplied, run_dir, warnings = ctx.supplied, ctx.out_dir, ctx.warnings
    results = dict(ctx.results)
    if failure is not None:
        for key, comp in _RESULT_KEYS.items():
            if key in results:
                continue
            art = _SUPPLIED_FOR.get(key)
            if comp in ran:
                why = f"not reached: run failed during {failure['stage']} ({failure['type']})"
            elif art and art in inputs:
                why = _supplied_reason(art)
            elif art and art in (supplied or {}):
                why = _supplied_reason(art) + ", but it failed to load -- see `error`"
            else:
                why = _not_selected(comp)
            results[key] = _skip(why)
    m1 = {"ingestion": m1_checks.to_report(record) if record else None, "localize": localize_info}
    if m2_read and str(m2_read.get("error") or "").startswith("refused"):
        m2_read_report = {"source": "refused", "target_mpp": m2_read.get("target_mpp"),
                          "scale_source": m2_read.get("scale_source"), "error": m2_read["error"]}
    elif m2_read:
        m2_read_report = dict(_read_report(m2_read), source="computed")
    elif (inputs.get("thumbnail") or {}).get("source") == "supplied":
        m2_read_report = {"source": "supplied", "target_mpp": inputs["thumbnail"].get("mpp"),
                          "achieved_mpp": None, "assumed_mpp": inputs["thumbnail"].get("mpp"),
                          "note": inputs["thumbnail"].get("mpp_source"), "error": None}
    else:
        m2_read_report = None
    m2 = {"read": m2_read_report}
    for key, mod in (("pen", m2_pen), ("tissue", m2_tissue), ("folds", m2_folds),
                     ("staining", m2_staining), ("focus", m2_focus)):
        r = results.get(key) or {}
        m2[key] = r if str(r.get("error") or "").startswith("skipped") else mod.to_report(r)
    m4 = {"stain_norm": (m4_norm.to_report(results["stain_norm"])
                         if not str((results.get("stain_norm") or {}).get("error", "")
                                    ).startswith("skipped") else results.get("stain_norm"))}
    gate = results.get("m3_gate") or {}
    m3 = {"status": gate.get("status"), "reason": gate.get("reason"),
          "level0_mpp": gate.get("level0_mpp"), "gate": gate.get("gate"),
          "tile_plane": gate.get("tile_plane")}
    tiles = results.get("tiles") or {}
    m3["tiles"] = (m3_tiles.to_report(tiles)
                   if not str(tiles.get("error", "")).startswith("skipped") else tiles)
    arts = results.get("artifacts") or {}
    m3["artifacts"] = (m3_artifacts.to_report(arts)
                       if not str(arts.get("error", "")).startswith("skipped") else arts)
    if results.get("tile_list") is not None:
        m3["n_tiles_selected"] = len(results["tile_list"])
    # Tile metrics refine tissue per tile. The optional chunk-refinement helper is not
    # part of the pipeline; retain an explicit cascade skip in the report.
    m3["cascade"] = _skip("separate chunk pass not in the flow; per-tile refinement runs inside "
                          "tile_metrics (plan Step 3 v2 S-3)")

    report = build_report(slide_id, slide_path, stain_type=stain_type, m1=m1, m2=m2, m3=m3, m4=m4,
                          timing_extra=stage_t, total_s=total_s, run_provenance=ctx.run_provenance)
    # A component counts as run when it produces a result. M3 components rejected by a gate
    # are recorded as gated, with their skip reason.
    def _err(key):
        return str((results.get(key) or {}).get("error", ""))
    reached = {comp for key, comp in _RESULT_KEYS.items() if comp in ran
               and not _err(key).startswith("skipped")}
    not_reached = {comp for key, comp in _RESULT_KEYS.items() if comp in ran
                   and _err(key).startswith("skipped: not reached")}
    if "tile_selection" in ran:
        if results.get("tile_list") is not None:
            reached.add("tile_selection")
        elif failure is not None and (results.get("m3_gate") or {}).get("ok") is not False:
            not_reached.add("tile_selection")
    # Partition requested components into run, not reached after a failure, and gated.
    gated = ran - reached - not_reached
    report["error"] = failure
    report["provenance"]["components_run"] = sorted(reached)
    report["provenance"]["components_not_reached"] = sorted(not_reached)
    report["provenance"]["components_gated"] = sorted(gated)
    report["provenance"]["components_skipped"] = sorted(set(spec.COMPONENTS) - ran)
    report["provenance"]["components_disabled_config"] = sorted(set(spec.COMPONENTS) - spec.default_run_set())
    report["provenance"]["degraded"] = {**plan["degraded"], **(results.get("_degraded") or {})}
    report["provenance"]["warnings"] = list(warnings if warnings is not None else plan["warnings"])
    report["provenance"]["stain_routing"] = results.get("_stain_routing")
    report["provenance"]["external_backends"] = results.get("_external_backends", {})
    report["provenance"]["grandqc_repo"] = results.get("_grandqc_repo")
    # Report execution facts and omissions; scientific interpretation belongs to SMEs.
    reasons: list = []
    observations = _ingestion_observations(record, localize_info)
    if report["provenance"].get("config_error"):
        reasons.append(report["provenance"]["config_error"])
    if failure is not None:
        reasons.append(f"run failed during {failure.get('stage')} ({failure.get('type')})")
    if report["provenance"]["degraded"]:
        observations.append(f"degraded: {sorted(report['provenance']['degraded'])}")
    if (localize_info or {}).get("verified") is False:
        reasons.append("localized copy failed verification")
    scale_src = str(((record or {}).get("acquisition") or {}).get("mpp_source") or "")
    if scale_src.startswith("derived"):
        observations.append(f"scale {scale_src}")
    routing = results.get("_stain_routing") or {}
    if routing.get("recognised") is False:
        observations.append(f"stain {routing.get('stain_type')!r} matched no configured vocabulary")
    if report["provenance"].get("stain_type_flag"):
        observations.append(report["provenance"]["stain_type_flag"])
    incomplete: list = []
    if results.get("_degraded"):
        incomplete.append(f"degraded component results: {sorted(results['_degraded'])}")
    failed_components = []
    for key, component in _RESULT_KEYS.items():
        if component not in reached:
            continue
        component_spec = spec.COMPONENTS[component]
        section = (report.get(component_spec["stage"]) or {}).get(component_spec["report_key"]) or {}
        error = section.get("error")
        if error and not str(error).startswith("skipped"):
            failed_components.append(component)
            reasons.append(f"{component} failed: {error}")
    if failed_components:
        incomplete.append(f"failed components: {sorted(failed_components)}")
    read_failed = (report.get("m3", {}).get("tiles") or {}).get("n_read_failed") or 0
    if "tile_metrics" in ran and read_failed:
        reasons.append(f"{read_failed} tile read(s) failed")
        incomplete.append("tile metrics are partial because tile reads failed")
    mask_error = (report.get("m3", {}).get("tiles") or {}).get("mask_write_error")
    if mask_error:
        incomplete.append(f"tissue_mask_20x not complete: {mask_error}")
    report["provenance"]["components_failed"] = sorted(failed_components)
    if gated:
        incomplete.append(f"gated: {sorted(gated)}")
    if not_reached:
        incomplete.append(f"not reached: {sorted(not_reached)}")
    report["provenance"]["warnings"] = list(dict.fromkeys(
        report["provenance"]["warnings"] + observations))
    report["provenance"]["bank"] = ctx.bank
    report["provenance"]["execution"] = {"complete": not incomplete and failure is None,
                                       "reasons": reasons + incomplete}
    report["provenance"]["inputs"] = inputs
    report["provenance"]["outputs"] = outputs
    report["provenance"]["out_dir"] = str(run_dir) if run_dir is not None else None
    return report


def _ingestion_observations(record, localize_info) -> list[str]:
    """Surface recorded acquisition facts without interpreting scientific suitability."""
    record = record or {}
    observations = []
    decision = record.get("decision") or {}
    if decision.get("status") not in (None, "pass", "not_checked"):
        observations.append(f"M1 decision {decision['status']}: "
                            f"{decision.get('quarantine_reason') or decision.get('flags')}")
    metadata = record.get("metadata") or {}
    if metadata.get("error_type"):
        observations.append(f"metadata lookup failed: {metadata.get('error')}")
    for problem in metadata.get("index_errors") or []:
        observations.append(f"metadata source problem: {problem.get('error', problem)}")
    for fact in ((record.get("checks") or {}).get("mpp") or {}).get("observations") or []:
        observations.append(f"{fact['code']}: {fact['message']}")
    localize_info = localize_info or {}
    if (localize_info.get("localized") and localize_info.get("verified") is None
            and localize_info.get("check") not in {"passthrough", "skipped"}):
        observations.append("localized copy verification unavailable: "
                            + str(localize_info.get("error") or localize_info.get("check")))
    return observations


def _hw(img):
    return (img.height, img.width) if img is not None else None


_slide_id = slide_id            # Use the shared slide identifier for the output folder.


def _read_report(plan: dict) -> dict:
    return {k: (list(plan[k]) if k == "plane_dims" and plan.get(k) else plan.get(k))
            for k in ("target_mpp", "source_mpp", "achieved_mpp", "resample_ratio", "direction",
                      "level", "plane_dims", "scale_source", "read_mode", "bands", "level_px",
                      "max_read_px", "error")}


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description="Run the Path-ND QC pipeline on one slide. With no --run_* flag, runs all components enabled in config.",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--slide", help="WSI path (local file, gs://, s3://, az:// or abfs[s]://)")
    ap.add_argument("--out", help="output directory for the report and artifacts")
    ap.add_argument("--stain", help="metadata stain type; OVERRIDES the metadata lookup")
    ap.add_argument("--metadata", action="append", metavar="PATH",
                    help="user-supplied metadata CSV (local, GCS, S3 or Azure); repeat for several files. "
                         "Omitting this skips metadata lookup.")
    ap.add_argument("--metadata_key", metavar="COL",
                    help="slide-key column in --metadata files; sniffed from the header when omitted")
    ap.add_argument("--no_metadata", action="store_true",
                    help="skip the metadata lookup entirely; the report records it as skipped, not "
                         "as a slide that was checked and not found")
    ap.add_argument("--bank", help="normalization reference bank; defaults to the resolved dataset")
    ap.add_argument("--norm_method", choices=list(m4_norm.METHODS), help="M4 method")
    ap.add_argument("--grandqc_python", help="Python executable for GrandQC; defaults to configured interpreter or this one")
    ap.add_argument("--pen_weights", help="WSISegQC pen model state_dict (.pt); overrides "
                                          "m2.pen.weights_path")
    ap.add_argument("--grandqc_repo", help="the GrandQC inference checkout "
                                           "(.../01_WSI_inference_OPENSLIDE_QC with models/qc/*.pth); "
                                           "defaults to m3.artifacts.repo_path when that exists")
    ap.add_argument("--no_save_artifacts", action="store_true",
                    help="compute but do not write masks/tiles/images")
    ap.add_argument("--no_model_download", action="store_true",
                    help="use existing model assets only; never download missing models")
    ap.add_argument("--list_components", action="store_true", help="print the surface and exit")
    ap.add_argument("-q", "--quiet", action="store_true",
                    help="log warnings and errors only (default: progress at INFO, each line "
                         "tagged with the run folder's name)")
    g = ap.add_argument_group("components (none given = all enabled in config; every selected component is required)")
    for key, s in spec.COMPONENTS.items():
        g.add_argument(s["flag"], dest=f"run_{key}", action="store_true",
                       help=f"{s['file']} [{s['stage']}]")
    for alias, members in spec.ALIASES.items():
        g.add_argument(alias, dest=alias.lstrip("-"), action="store_true",
                       help=f"= {', '.join(members)}")
    a = ap.add_argument_group("supplied artifacts (.png/.npy for masks, .json for lists)")
    for name, art in spec.ARTIFACTS.items():
        a.add_argument(art["flag"], dest=f"in_{name}", metavar="PATH", help=art["help"])
    return ap


class PipelineInterrupted(KeyboardInterrupt):
    """CLI termination request, recorded through the normal interrupted-run path."""


def main(argv: list[str] | None = None) -> int:
    """Install signal handling only for the CLI, restoring the caller's handler afterwards."""
    if threading.current_thread() is not threading.main_thread():
        return _main(argv)
    previous = signal.getsignal(signal.SIGTERM)

    def interrupted(signum, frame):
        # Let the first termination request finish publishing the failure record.
        # The batch supervisor can still enforce its hard deadline with SIGKILL.
        signal.signal(signal.SIGTERM, signal.SIG_IGN)
        raise PipelineInterrupted(f"received signal {signum}")

    signal.signal(signal.SIGTERM, interrupted)
    try:
        return _main(argv)
    except KeyboardInterrupt:
        return 130
    finally:
        signal.signal(signal.SIGTERM, previous)


def _main(argv: list[str] | None = None) -> int:
    ap = build_parser()
    args = ap.parse_args(argv)
    # Enable download and tile-loop progress with run identifiers unless logging is already configured.
    configure_logging(args.quiet)
    if args.list_components:
        print(spec.usage_summary())
        return 0
    if not args.slide:
        ap.error("--slide is required (or use --list_components)")
    if args.no_metadata and (args.metadata or args.metadata_key):
        ap.error("--no_metadata cannot be combined with --metadata/--metadata_key; "
                 "one skips the lookup, the other configures it")
    if args.metadata_key and not args.metadata:
        # Everything else is validated before the slide is opened; a flag that quietly does nothing
        # is exactly the failure this pre-flight exists to prevent.
        ap.error("--metadata_key only applies to --metadata files; pass --metadata PATH too")

    selected = {k for k in spec.COMPONENTS if getattr(args, f"run_{k}")}
    aliases = {a for a in spec.ALIASES if getattr(args, a.lstrip("-"))}
    supplied = {n: getattr(args, f"in_{n}") for n in spec.ARTIFACTS
                if getattr(args, f"in_{n}")}
    run_set = spec.resolve_run_set(selected, aliases)
    # run() plans with the resolved backend configuration. Planning errors raise ValueError;
    # warnings reach the callback before slide I/O.

    def _warn(message):
        print(f"warning: {message}", file=sys.stderr)

    try:
        r = run(args.slide, out_dir=args.out, stain_type=args.stain, bank=args.bank,
                norm_method=args.norm_method, components=run_set, supplied=supplied,
                grandqc_repo=args.grandqc_repo, grandqc_python=args.grandqc_python,
                pen_weights=args.pen_weights, save_artifacts=not args.no_save_artifacts,
                metadata_paths=args.metadata, metadata_key=args.metadata_key,
                metadata_enabled=False if args.no_metadata else None, warn=_warn,
                download_models=not args.no_model_download)
    except RunFailed as exc:
        # Processing failures exit 1 and retain available reports; invalid arguments exit 2.
        f = exc.failure
        print(f"error: run failed during {f['stage']}: {f['type']}: {f['message']}", file=sys.stderr)
        if f["type"] in ("RuntimeError",) and ("could not open" in f["message"]
                                              or "could not localize" in f["message"]):
            print(f"  --slide expects a readable WSI path: a local file or GCS, S3 or Azure object URI.\n"
                  f"  got: {args.slide}", file=sys.stderr)
        if exc.report_path:
            print(f"report (FAILED run; see its `error` block) -> {exc.report_path}", file=sys.stderr)
        return 1
    except (RuntimeError, ValueError) as exc:
        # Pre-flight refusal: a bad command, nothing touched, nothing written.
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:  # noqa: BLE001 - a bug in the pipeline, not in the command: exit 1
        print(f"error: {type(exc).__name__}: {exc}", file=sys.stderr)
        traceback.print_exc()
        return 1

    rep = r["report"]
    print(f"components: {', '.join(sorted(run_set))}")
    rd = rep["m2"].get("read") or {}
    if rd.get("level") is not None:
        print(f"read: {rd['target_mpp']} um/px from L{rd['level']} "
              f"({rd['direction']} x{rd['resample_ratio']:.4f}) -> plane {rd['plane_dims']}")
    elif rd:
        print(f"read: {rd.get('source')}: {rd.get('error') or rd.get('note')}")
    tm = rep["timing"]
    print(f"timing: total {tm['total_s']:.1f}s  " +
          " · ".join(f"{k} {v}" for k, v in tm["stages"].items() if v))
    for name, meta in (rep["provenance"].get("outputs") or {}).items():
        print(f"  wrote {name}: {meta.get('path')}")
    print(f"report -> {r['report_path']}")
    if r.get("out_dir") and (Path(r["out_dir"]) / "index.html").is_file():
        print(f"browse -> {Path(r['out_dir']) / 'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
